export const ON = "ON";
export const DROP = "DROP";

export const FORGOT_PENDING = "FORGOT_PENDING";
export const FORGOT_SUCCESS = "FORGOT_SUCCESS";
export const FORGOT_FAILED = "FORGOT_FAILED";

export const RESET_PENDING = "RESET_PENDING";
export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_FAILED = "RESET_FAILED";

export const SET_LOADING = "SET_LOADING";
export const SET_LOGIN = "SET_LOGIN";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

export const GETTING_ROLES_SUCCESS = "GETTING_ROLES_SUCCESS";
export const GETTING_ROLES_ERROR = "GETTING_ROLES_ERROR";

export const CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const CREATE_ROLE_ERROR = "CREATE_ROLE_ERROR";

export const DELETE_ROLE_SUCCESS = "DELETE_ROLE SUCCESS";
export const DELETE_ROLE_ERROR = "DELETE_ROLE_ERROR";

export const EDIT_ROLE_SUCCESS = "EDIT_ROLE_SUCCESS";
export const EDIT_ROLE_ERROR = "EDIT_ROLE_ERROR";
export const REGISTER_PENDING = "REGISTER_PENDING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const FETCH_OPERATOR_LOADING = "FETCH_OPERATOR_LOADING";
export const FETCHED_OPERATOR = "FETCHED_OPERATOR";
export const ERROR_FETCH_OPERATOR = "ERROR_FETCH_OPERATOR";
export const DELETE_OPERATOR = "DELETE_OPERATOR";
export const DELETE_OPERATOR_SUCCESS = "DELETE_OPERATOR_SUCCESS";
export const DELETE_OPERATOR_ERROR = "DELETE_OPERATOR_ERROR";
export const EDIT_OPERATOR_SUCCESS = "EDIT_OPERATOR_SUCCESS";
export const EDIT_OPERATOR = "EDIT_OPERATOR";
export const EDIT_OPERATOR_ERROR = "EDIT_OPERATOR_ERROR";
export const FETCH_DRIVER_LOADING = "FETCH_DRIVER_LOADING";
export const FETCHED_DRIVER = "FETCHED_DRIVER";
export const ERROR_FETCH_DRIVER = "ERROR_FETCH_DRIVER";
export const DELETE_DRIVER = "DELETE_DRIVER";
export const DELETE_DRIVER_SUCCESS = "DELETE_DRIVER_SUCCESS";
export const DELETE_DRIVER_ERROR = "DELETE_DRIVER_ERROR";
export const EDIT_DRIVER_SUCCESS = "EDIT_DRIVER_SUCCESS";
export const EDIT_DRIVER = "EDIT_DRIVER";
export const EDIT_DRIVER_ERROR = "EDIT_DRIVER_ERROR";
export const REGISTER_DRIVER_PENDING = "REGISTER_DRIVER_PENDING";
export const REGISTER_DRIVER_SUCCESS = "REGISTER_DRIVER_SUCCESS";
export const REGISTER_DRIVER_FAILED = "REGISTER_DRIVER_FAILED";
export const GET_DRIVERS_PENDING = "GET_DRIVERS_PENDING";
export const GET_DRIVERS_SUCCESS = "GET_DRIVERS_SUCCESS";
export const GET_DRIVERS_FAILED = "GET_DRIVERS_FAILED";
export const ASSIGN_BUSDRIVER_SUCCESS = "ASSIGN_BUSDRIVER_SUCCESS";
export const ASSIGN_BUSDRIVER_FAILED = "ASSING_BUSDRIVER_FAILED";
export const UNASSIGN_BUSDRIVER_SUCCESS = "UNASSIGN_BUSDRIVER_SUCCESS";
export const UNASSIGN_BUSDRIVER_FAILED = "UNASSIGNED_BUSDRIVER_SUCCESS";
export const GET_BUS_PENDING = "GET_BUS_PENDING";
export const GET_BUS_SUCCESS = "GET_BUS_SUCCESS";
export const GET_BUS_FAILED = "GET_BUS_FAILED";
