export const ON = 'ON';
export const DROP = 'DROP';

export const FORGOT_PENDING = 'FORGOT_PENDING';
export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOT_FAILED = 'FORGOT_FAILED';

export const RESET_PENDING = 'RESET_PENDING';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAILED = 'RESET_FAILED';

export const SET_LOADING = 'SET_LOADING';
export const SET_LOGIN = 'SET_LOGIN';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const GETTING_ROLES_SUCCESS = 'GETTING_ROLES_SUCCESS';
export const GETTING_ROLES_ERROR = 'GETTING_ROLES_ERROR';

export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const CREATE_ROLE_ERROR = 'CREATE_ROLE_ERROR';

export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE SUCCESS';
export const DELETE_ROLE_ERROR = 'DELETE_ROLE_ERROR';

export const EDIT_ROLE_SUCCESS = 'EDIT_ROLE_SUCCESS';
export const EDIT_ROLE_ERROR = 'EDIT_ROLE_ERROR';
